server:
  port: 8081

spring:
  application:
    name: Login_System
  datasource:
    url: jdbc:mysql://localhost:3306/ID_Sys
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  aes:
    secret_key: ${AES_SECRET_KEY}

mybatis:
  mapper-locations: classpath:mappers/*.XML